#!/bin/bash
file="/sys/class/backlight/intel_backlight/brightness"
current=$(cat "$file")
max=$(cat "/sys/class/backlight/intel_backlight/max_brightness")
new="$current"

if [ "$1" = "+" ] && [ $max -neq $current ]; then
    pourcent=((max*0.05))
	#new=$(( current + $2 ))
fi

echo "$new" | tee "$file"
